spring:
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port:
    8200